### ISSUE TITLE
Problem with install stomp.py version 3.1.5 in ubuntu 16.04

### ISSUE THREAD

**Issue by tacnoman** [jasonrbriggs/stomp.py#104]
I need install the stomp.py (version 3.1.5).
I'm using ubuntu, version 16.04.

sudo pip install stomp.py==3.1.5                                                                                                                                               
The directory '/home/tacnoman/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/tacnoman/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting stomp.py==3.1.5
  Downloading stomp.py-3.1.5.tar.gz (94kB)
    100% |████████████████████████████████| 102kB 989kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-FGqOzb/stomp.py/setup.py", line 12, in <module>
        import stomp
      File "stomp/__init__.py", line 16, in <module>
        import connect, listener, exception
      File "stomp/connect.py", line 19, in <module>
        DEFAULT_SSL_VERSION = ssl.PROTOCOL_SSLv3
    AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-FGqOzb/stomp.py/

How can I do to solve this?
Thanks for this.

**Comment by jasonrbriggs** [comment]
Works fine for me with the latest version of 3.1 (3.1.7):

```
(python2.7) jasonbriggs@devuan:~$ pip install stomp.py==3.1.7
Collecting stomp.py==3.1.7
  Downloading stomp.py-3.1.7.tar.gz
Building wheels for collected packages: stomp.py
  Running setup.py bdist_wheel for stomp.py ... done
  Stored in directory: /home/jasonbriggs/.cache/pip/wheels/b7/d0/cd/6d5a5d372d225a250a31127a5032c8df5472bee467db367829
Successfully built stomp.py
Installing collected packages: stomp.py
Successfully installed stomp.py-3.1.7
```

Python3 as well:
```
(python3.4) jasonbriggs@devuan:~$ pip install stomp.py==3.1.7
Collecting stomp.py==3.1.7
  Using cached stomp.py-3.1.7.tar.gz
Building wheels for collected packages: stomp.py
  Running setup.py bdist_wheel for stomp.py ... done
  Stored in directory: /home/jasonbriggs/.cache/pip/wheels/b7/d0/cd/6d5a5d372d225a250a31127a5032c8df5472bee467db367829
Successfully built stomp.py
Installing collected packages: stomp.py
Successfully installed stomp.py-3.1.7
```

**Comment by circlecheung** [comment]
same problem with ubuntu 16.0.4 

(pvrs)zhang:mcms$ pip install stomp.py
Downloading/unpacking stomp.py
  Downloading stomp.py-4.0.11.tar.gz (83kB): 83kB downloaded
  Running setup.py egg_info for package stomp.py
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/zhang/pvrs/build/stomp.py/setup.py", line 12, in <module>
        import stomp
      File "stomp/__init__.py", line 16, in <module>
        import connect, listener, exception, transport, protocol
      File "stomp/connect.py", line 1, in <module>
        from transport import *
      File "stomp/transport.py", line 27, in <module>
        DEFAULT_SSL_VERSION = ssl.PROTOCOL_SSLv3
    AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/zhang/pvrs/build/stomp.py/setup.py", line 12, in <module>

    import stomp

  File "stomp/__init__.py", line 16, in <module>

    import connect, listener, exception, transport, protocol

  File "stomp/connect.py", line 1, in <module>

    from transport import *

  File "stomp/transport.py", line 27, in <module>

    DEFAULT_SSL_VERSION = ssl.PROTOCOL_SSLv3

AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

**Comment by asfaltboy** [comment]
@circlecheung I believe the soluition is in  4.0.16 as in the issue #30
