### ISSUE TITLE
keep getting utf-8 decode error from Stompreceiverthread

### ISSUE THREAD

**Issue by sebastienpattyn93** [jasonrbriggs/stomp.py#175]
I have a python script that will read data from a RSS feed every 10 minutes and then sends it to activeMQ using STOMP. I added some prints to check if the code is failing somewhere but erverything get's executed fine. I do get an error in my cli after executing my script.
```python
def main():
    recent_id = '0'
    while True:
        d = feedparser.parse(endpoint)
        if recent_id == d.entries[0].id:
            time.sleep(600)
        else:
            recent_id = d.entries[0].id
            conn = stomp.Connection([('x.x.x.x', 61616)])
            conn.start()
            conn.connect()
            print('connected')
            for entry in d.entries:
                conn.send(destination='tengu-topic', body=str(entry))
            print('All items done')
            conn.disconnect()
            print('disconnected')
            time.sleep(600)

if __name__ == '__main__':
    main()

```
This is my CLI output with the prints and the error. I changed my code by changing my entry to a json that I'm sending instead of a string but I got the same error. 

```
connected
All items done
disconnected
Exception in thread StompReceiverThread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/stomp/transport.py", line 332, in __receiver_loop
    f = utils.parse_frame(frame)
  File "/usr/local/lib/python3.5/dist-packages/stomp/utils.py", line 138, in parse_frame
    preamble = decode(frame[0:preamble_end])
  File "/usr/local/lib/python3.5/dist-packages/stomp/backward3.py", line 29, in decode
    return byte_data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 1: invalid start byte
```

**Comment by sebastienpattyn93** [comment]
there was an issue on my activeMQ instance that caused this problem.
