### ISSUE TITLE
Race condition makes restart/reconnect impossible in some cases

### ISSUE THREAD

**Issue by bkjones** [jasonrbriggs/stomp.py#208]
I'm finding that if I create a StompConnection12 object with reconnect_sleep_initial set to its default value of 0.1, then if I quickly stop and restart activemq while my listener is running, it will fail to properly connect. However, if I set reconnect_sleep_initial=10, the code generally reconnects successfully. 

I suspect there's some kind of race condition between maybe the wait_on_connection and receiver loop code, where wait_on_connection's thread condition it's waiting on is being awakened by the receiver loop's 'disconnect' notification from the previous disconnect, or maybe the receiver loop's setting of self.running to False from a previous disconnection or something, but I can't determine exactly which. 

My code is below. Any advice is welcome.

```
def start_consumer():
    connection = stomp.StompConnection12([(STOMP_HOST, STOMP_PORT)],
                                         heartbeats=(STOMP_HEARTBEAT_SEND_MIN_MS, STOMP_HEARTBEAT_RECV_MAX_MS),
                                         reconnect_attempts_max=CONNECT_RETRIES_MAX,
                                         reconnect_sleep_initial=10,
                                         timeout=10)
    listener = StompConsumer()
    connection.set_listener('StompConsumer', listener)
    connection.start()
    connection.connect(STOMP_USER, STOMP_PASS, wait=True)
    connection.subscribe(STOMP_QUEUE, id=1)
    return connection


if __name__ == '__main__':
    conn = start_consumer()
    while True:
        if conn.is_connected():
            time.sleep(2)
        else:
            conn = start_consumer()
```

Some log output from a failed reconnect. I added extra logging statements: 

```
INFO:stomp.py:Attempting connection to host localhost, port 61613
INFO:stomp.py:Established connection to host localhost, port 61613
INFO:stomp.py:Starting receiver loop
DEBUG:stomp.py:Sending frame: ['STOMP', '\n', 'accept-version:1.2\n', 'heart-beat:1000,3000\n', 'host:localhost\n', 'login:admin\n', 'passcode:admin\n', '\n', b'\x00']
DEBUG:stomp.py:waiting for connection. is_connected() == False and self.running == True
DEBUG:stomp.py:Waiting for connection....
DEBUG:stomp.py:Setting self.running to False in receiver loop
INFO:stomp.py:Receiver loop ended
DEBUG:stomp.py:is_connected() = False and self.running = False at end of wait_for_connection
Traceback (most recent call last):
  File "/Users/brianjones/git/stomp-invalidation-consumer/stomp_consumer/consumer.py", line 89, in <module>
    conn = start_consumer()
  File "/Users/brianjones/git/stomp-consumer/stomp_consumer/consumer.py", line 78, in start_consumer
    connection.connect(STOMP_USER, STOMP_PASS, wait=True)
  File "/Users/brianjones/venv/stomp-consumer/lib/python3.6/site-packages/stomp/connect.py", line 215, in connect
    Protocol12.connect(self, *args, **kwargs)
  File "/Users/brianjones/venv/stomp-consumer/lib/python3.6/site-packages/stomp/protocol.py", line 518, in connect
    self.transport.wait_for_connection(wait_timeout)
  File "/Users/brianjones/venv/stomp-consumer/lib/python3.6/site-packages/stomp/transport.py", line 327, in wait_for_connection
    raise exception.ConnectFailedException()
stomp.exception.ConnectFailedException
```

**Comment by madkote** [comment]
+1 have same issue, thought I am do something wrong...

**Comment by madkote** [comment]
@bkjones btw, do you handle reconnect with a listener?

**Comment by jasonrbriggs** [comment]
Don't think this is an issue in the latest version - at least I've been unable to reproduce the problem with an hour or so of trying.
