### ISSUE TITLE
I can run the sample

### ISSUE THREAD

**Issue by cristicmf** [jasonrbriggs/stomp.py#236]
that is the message
`Traceback (most recent call last):
  File "test.py", line 15, in <module>
    conn.connect('root', '123456', wait=True)
  File "/usr/lib/python2.7/site-packages/stomp.py-4.1.22-py2.7.egg/stomp/connect.py", line 176, in connect
    Protocol11.connect(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/stomp.py-4.1.22-py2.7.egg/stomp/protocol.py", line 338, in connect
    self.transport.wait_for_connection()
  File "/usr/lib/python2.7/site-packages/stomp.py-4.1.22-py2.7.egg/stomp/transport.py", line 330, in wait_for_connection
    raise exception.ConnectFailedException()
stomp.exception.ConnectFailedException`

**Comment by jasonrbriggs** [comment]
Can't really help with this because you haven't included any information about what message server you're using, but that exception doesn't look out of the ordinary -- simply put, it can't connect to the server.
