### ISSUE TITLE
TypeError in Transport

### ISSUE THREAD

**Issue by seepa** [jasonrbriggs/stomp.py#29]
Hi, I've spotted a small bug:
In `transport.py` line 174 `len(f.body)` is called, but f.body can be `None` which leads to an exception:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "venv/lib/python3.4/site-packages/stomp/transport.py", line 300, in __receiver_loop
    self.process_frame(f, frame)
  File "venv/lib/python3.4/site-packages/stomp/transport.py", line 174, in process_frame
    log.info("Received frame: %r, headers=%r, len(body)=%r", f.cmd, f.headers, len(f.body))
TypeError: object of type 'NoneType' has no len()

```

best regards,
Patrick

**Comment by jasonrbriggs** [comment]
Fixed in 4.0.15
