### ISSUE TITLE
Seeing three SSL library errors on attempt_connection

### ISSUE THREAD

**Issue by tr0yspradling** [jasonrbriggs/stomp.py#328]
```
Traceback (most recent call last):
--
  | File "/var/lib/stomplib/transport.py", line 773, in attempt_connection
  | self.socket = tls_context.wrap_socket(self.socket, server_hostname=host_and_port[0])
  | File "/opt/rh/python27/root/usr/lib64/python2.7/ssl.py", line 369, in wrap_socket
  | _context=self)
  | File "/opt/rh/python27/root/usr/lib64/python2.7/ssl.py", line 619, in __init__
  | self.do_handshake()
  | File "/opt/rh/python27/root/usr/lib64/python2.7/ssl.py", line 848, in do_handshake
  | self._sslobj.do_handshake()
  | SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:727)
  | ERROR:stomp.py:[SSL: EXCESSIVE_MESSAGE_SIZE] excessive message size (_ssl.c:727)
```
```
Traceback (most recent call last):
--
  | File "/var/lib/stomplib/transport.py", line 773, in attempt_connection
  | self.socket = tls_context.wrap_socket(self.socket, server_hostname=host_and_port[0])
  | File "/opt/rh/python27/root/usr/lib64/python2.7/ssl.py", line 369, in wrap_socket
  | _context=self)
  | File "/opt/rh/python27/root/usr/lib64/python2.7/ssl.py", line 619, in __init__
  | self.do_handshake()
  | File "/opt/rh/python27/root/usr/lib64/python2.7/ssl.py", line 848, in do_handshake
  | self._sslobj.do_handshake()
  | SSLError: [SSL: SSLV3_ALERT_UNEXPECTED_MESSAGE] sslv3 alert unexpected message (_ssl.c:727)
```
```
Traceback (most recent call last):
--
  | File "/var/lib/stomplib/transport.py", line 773, in attempt_connection
  | self.socket = tls_context.wrap_socket(self.socket, server_hostname=host_and_port[0])
  | File "/opt/rh/python27/root/usr/lib64/python2.7/ssl.py", line 369, in wrap_socket
  | _context=self)
  | File "/opt/rh/python27/root/usr/lib64/python2.7/ssl.py", line 619, in __init__
  | self.do_handshake()
  | File "/opt/rh/python27/root/usr/lib64/python2.7/ssl.py", line 848, in do_handshake
  | self._sslobj.do_handshake()
  | SSLEOFError: EOF occurred in violation of protocol (_ssl.c:727)

```

**Comment by tr0yspradling** [comment]
Temporary workaround was to create a new connection object and reattach a listener with `on_receiver_loop_completed`.

**Comment by tr0yspradling** [comment]
Changed `DEFAULT_SSL_VERSION` from `ssl.PROTOCOL_TLSv1` to `ssl.PROTOCOL_TLSv2` & it seems to have resolved the problem (I THINK). Doing more testing to make sure this is the case. 

Only issue now is gunicorn is having issues sometimes & I'm getting worker timeouts. I had 4 container restarts when deploying to kubernetes but it eventually worked itself out. Possibly hung connection attempt?

**Comment by tr0yspradling** [comment]
Now that I think about it, that wouldn't be the issue because stomp.py spins off another thread to do the connecting. So gunicorn wouldn't be waiting for the connection... I think.

**Comment by tr0yspradling** [comment]
Nevermind. I thought it was resolved because the listener was running for nearly 10x longer than normal, then started disconnecting because of SSL errors & heartbeat timeouts.

**Comment by pallavg** [comment]
I am also experiencing a similar issue in stomp 6.1. I have a daemon running that just connects to ActiveMQ and waits for messages. After a day or so, I notice the connection drops, and when it tries to reconnect all three IP addresses are refused for some reason. I have to restart the daemon as a workaround. Here is the log file showing the behavior



```
[2020-09-29 20:51:27]    tvpv_portal.services.msgbkr     INFO - Create ActiveMQ (consumer) connection for (receiving) messages
[2020-09-29 20:51:27]                       stomp.py     INFO - attempt reconnection (True, None, 0)
[2020-09-29 20:51:27]                       stomp.py     INFO - Attempting connection to host XXX, port 8501
[2020-09-29 20:51:27]                       stomp.py     INFO - Established connection to host XXX, port 8501
[2020-09-29 20:51:27]                       stomp.py     INFO - Starting receiver loop (<Thread(Thread-1, started daemon 140737321330432)>)
[2020-09-29 20:51:27]                       stomp.py     INFO - Created thread <Thread(Thread-1, started daemon 140737321330432)> using func <function default_create_thread at 0x7ffff6be77a0>
[2020-09-29 20:51:27]                       stomp.py     INFO - Sending frame: 'STOMP'
[2020-09-29 20:51:27]                       stomp.py     INFO - Received frame: 'CONNECTED', len(body)=0
[2020-09-29 20:51:27]                       stomp.py     INFO - Sending frame: 'SUBSCRIBE'
[2020-09-30 00:32:56]                       stomp.py     INFO - Receiver loop ended
[2020-09-30 00:32:56]    tvpv_portal.services.msgbkr     INFO - Attempt reconnect to ActiveMQ
[2020-09-30 00:32:56]                       stomp.py     INFO - attempt reconnection (True, None, 0)
[2020-09-30 00:32:56]                       stomp.py     INFO - Attempting connection to host 10.64.67.238, port 8501
[2020-09-30 00:32:56]                       stomp.py  WARNING - Could not connect to host 10.64.67.238, port 8501
Traceback (most recent call last):
  File "/nfs/pdx/disks/mpe_tvpv_002/flash_releases/latest/lib/python3.7/site-packages/stomp/transport.py", line 737, in attempt_connection
    self.socket = socket.create_connection(host_and_port, self.__timeout)
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2020-09-30 00:32:56]                       stomp.py     INFO - Attempting connection to host XXX, port 8501
[2020-09-30 00:32:56]                       stomp.py  WARNING - Could not connect to host XXX, port 8501
Traceback (most recent call last):
  File "/nfs/pdx/disks/mpe_tvpv_002/flash_releases/latest/lib/python3.7/site-packages/stomp/transport.py", line 737, in attempt_connection
    self.socket = socket.create_connection(host_and_port, self.__timeout)
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2020-09-30 00:32:56]                       stomp.py     INFO - Attempting connection to host XXX, port 8501
[2020-09-30 00:32:56]                       stomp.py  WARNING - Could not connect to host XXX, port 8501
Traceback (most recent call last):
  File "/nfs/pdx/disks/mpe_tvpv_002/flash_releases/latest/lib/python3.7/site-packages/stomp/transport.py", line 737, in attempt_connection
    self.socket = socket.create_connection(host_and_port, self.__timeout)
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by tr0yspradling** [comment]
@pallavg This seems to be a separate issue, could you open a new issue to track this?

**Comment by tr0yspradling** [comment]
Also in regards to the SSL problems, I believe this is an issue with gunicorn having multiple workers/threads running. I added some randomized sleep timers to connect, subscribe, ack/nack responses & it seems to have "resolved" the SSL errors. 

Not entirely sure if this is a problem on the client locally, or on the activemq umb.

**Comment by tr0yspradling** [comment]
Seeing a new issue causing random disconnects now though: #329

**Comment by jasonrbriggs** [comment]
Do you get the same issue with Python3?   Unlikely to be the issue, but since stomp.py is no longer supporting py2.x would be interested to know if this is still an issue with Py3.

**Comment by tr0yspradling** [comment]
I originally had the last version available for python2 but I cloned the repo & backported all the changes from `master`. I had seen some older issues on github about the disconnects & reconnects so I figured there were some other updates that I may not be aware of.
