### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'recv'

### ISSUE THREAD

**Issue by tr0yspradling** [jasonrbriggs/stomp.py#329]
```

DEBUG:stomp.py:Sending frame: ['SUBSCRIBE', '\n', 'ack:client-individual\n', 'destination:/topic/foo\n', 'id:foo-dev-phx2-1008-lrwmk-yqseo0w0\n', '\n', '\x00']
--
  | DEBUG:stomp.py:socket read error
  | Traceback (most recent call last):
  | File "/var/pylug/lib/stomplib/transport.py", line 386, in __read
  | c = self.receive()
  | File "/var/pylug/lib/stomplib/transport.py", line 662, in receive
  | return self.socket.recv(self.__recv_bytes)
  | AttributeError: 'NoneType' object has no attribute 'recv'
  | DEBUG:stomp.py:nothing received, raising CCE
  | INFO:stomp.py:Receiver loop ended
  | DEBUG:foo-client.umb:UMB (foo-dev-phx2-1008-lrwmk-l3wyg9wv): Subscribing academy client to "/topic/foo".
  | DEBUG:foo-client.umb:UMB (foo-dev-phx2-1008-lrwmk-l3wyg9wv): Send -- "{cmd=SUBSCRIBE,headers=[{'ack': 'client-individual', 'destination': '/topic/foo', 'id': 'foo-dev-phx2-1008-lrwmk-l3wyg9wv'}],body=}"
  | DEBUG:stomp.py:Sending frame: ['SUBSCRIBE', '\n', 'ack:client-individual\n', 'destination:/topic/foo\n', 'id:foo-dev-phx2-1008-lrwmk-l3wyg9wv\n', '\n', '\x00']
  | DEBUG:stomp.py:socket read error
  | Traceback (most recent call last):
  | File "/var/pylug/lib/stomplib/transport.py", line 386, in __read
  | c = self.receive()
  | File "/var/pylug/lib/stomplib/transport.py", line 662, in receive
  | return self.socket.recv(self.__recv_bytes)
  | AttributeError: 'NoneType' object has no attribute 'recv'
  | DEBUG:stomp.py:nothing received, raising CCE
  | INFO:stomp.py:Receiver loop ended
```

**Comment by jasonrbriggs** [comment]
Closing - without a reproducible test case, won't be looking into this.
