### ISSUE TITLE
During reconnection, all three attempts fail

### ISSUE THREAD

**Issue by pallavg** [jasonrbriggs/stomp.py#330]
I am experiencing an issue in stomp 6.1. I have a daemon running that just connects to ActiveMQ and waits for messages. After a day or so, I notice the connection drops, and when it tries to reconnect all three IP addresses are refused for some reason. I have to restart the daemon as a workaround. Here is the log file showing the behavior

Running on python 3.7.X

```
[2020-09-29 20:51:27]    tvpv_portal.services.msgbkr     INFO - Create ActiveMQ (consumer) connection for (receiving) messages
[2020-09-29 20:51:27]                       stomp.py     INFO - attempt reconnection (True, None, 0)
[2020-09-29 20:51:27]                       stomp.py     INFO - Attempting connection to host XXX, port 8501
[2020-09-29 20:51:27]                       stomp.py     INFO - Established connection to host XXX, port 8501
[2020-09-29 20:51:27]                       stomp.py     INFO - Starting receiver loop (<Thread(Thread-1, started daemon 140737321330432)>)
[2020-09-29 20:51:27]                       stomp.py     INFO - Created thread <Thread(Thread-1, started daemon 140737321330432)> using func <function default_create_thread at 0x7ffff6be77a0>
[2020-09-29 20:51:27]                       stomp.py     INFO - Sending frame: 'STOMP'
[2020-09-29 20:51:27]                       stomp.py     INFO - Received frame: 'CONNECTED', len(body)=0
[2020-09-29 20:51:27]                       stomp.py     INFO - Sending frame: 'SUBSCRIBE'
[2020-09-30 00:32:56]                       stomp.py     INFO - Receiver loop ended
[2020-09-30 00:32:56]    tvpv_portal.services.msgbkr     INFO - Attempt reconnect to ActiveMQ
[2020-09-30 00:32:56]                       stomp.py     INFO - attempt reconnection (True, None, 0)
[2020-09-30 00:32:56]                       stomp.py     INFO - Attempting connection to host 10.64.67.238, port 8501
[2020-09-30 00:32:56]                       stomp.py  WARNING - Could not connect to host 10.64.67.238, port 8501
Traceback (most recent call last):
  File "/nfs/pdx/disks/mpe_tvpv_002/flash_releases/latest/lib/python3.7/site-packages/stomp/transport.py", line 737, in attempt_connection
    self.socket = socket.create_connection(host_and_port, self.__timeout)
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2020-09-30 00:32:56]                       stomp.py     INFO - Attempting connection to host XXX, port 8501
[2020-09-30 00:32:56]                       stomp.py  WARNING - Could not connect to host XXX, port 8501
Traceback (most recent call last):
  File "/nfs/pdx/disks/mpe_tvpv_002/flash_releases/latest/lib/python3.7/site-packages/stomp/transport.py", line 737, in attempt_connection
    self.socket = socket.create_connection(host_and_port, self.__timeout)
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2020-09-30 00:32:56]                       stomp.py     INFO - Attempting connection to host XXX, port 8501
[2020-09-30 00:32:56]                       stomp.py  WARNING - Could not connect to host XXX, port 8501
Traceback (most recent call last):
  File "/nfs/pdx/disks/mpe_tvpv_002/flash_releases/latest/lib/python3.7/site-packages/stomp/transport.py", line 737, in attempt_connection
    self.socket = socket.create_connection(host_and_port, self.__timeout)
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/nfs/pdx/disks/mpe_tvpv_002/sw_tools/anaconda3/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by jasonrbriggs** [comment]
Are you heartbeating the connection to keep it open?  And after it disconnects do you see anything listening on that port (on either side perhaps), i.e. if you run netstat and grep for the relevant port.

**Comment by pallavg** [comment]
1. No, no heartbeat as far I can tell. I'm using default settings like this:

```
class ConnectionFailureListener(stomp.ConnectionListener):
    """This class is used to re-establish a connection to the ActiveMQ server in case of disconnect."""

    def __init__(self, conn):
        """Initialization.

        Args:
            conn -- Connection object
        """

        self._conn = conn

    def on_disconnected(self):
        """Reconnect to MQ if there is a connection failure."""

        log.info('Attempt reconnect to ActiveMQ')
        self._conn.connect()


class MsgBkr(object):

    def __init__(self, producer=True, conn_name='django_activemq'):
        """Initialization.

        Args:
            producer -- Whether this connection is a producer (writer) or consumer (reader)
        """

        # 'django_activemq' is the global producer queue. Consumers have their own queue which user should provide.
        if producer:
            assert conn_name == 'django_activemq'
        else:
            assert conn_name != 'django_activemq'

        self._producer = producer
        self._data = get_credentials()
        self._conn_name = conn_name
        conn = self._create_connection()
        self._conn = conn

        # Add listeners.
        self._conn.set_listener('connection_failure_listener', ConnectionFailureListener(self._conn))

    def _create_connection(self):
        """Create connection instance to ActiveMQ message broker.

        Returns:
            A Stomp connection object or None
        """

        # Type of connection.
        if self._producer:
            conn_type, conn_purpose = 'producer', 'sending'
        else:
            conn_type, conn_purpose = 'consumer', 'receiving'

        # Create SSL connection.
        log.info('Create ActiveMQ (%s) connection for (%s) messages', conn_type, conn_purpose)
        try:
            conn = stomp.Connection(self._data[self._conn_name]['hosts'])
            conn.set_ssl(for_hosts=self._data[self._conn_name]['hosts'], ssl_version=ssl.PROTOCOL_TLS)
        except stomp.exception.ConnectFailedException:
            log.critical('Unable to create ActiveMQ connection; check host ip/port and/or user/pass')
            conn = None

        return conn

    def connect(self):
        """Connect to ActiveMQ with user credentials.

        Note: This function should be called AFTER all listerners have been registered (w/ set_listener).
        """

        if self._conn is None:
            log.critical('ActiveMQ connection is None')
            return

        # If already connected, disconnect first. Then, reconnect.
        if self._conn.is_connected():
            self._conn.disconnect()

        # Producers can write to queue. Consumers can only read from queue.
        # NOTE: In both cases, we will use the '_rw' user. If there is a long period of inactivity, the queue gets
        # removed in DBaaS (not deleted). If we try to access with '_ro' user, we get an error saying we do not
        # have permission to create queue with '_ro' user.
        k = 'rw'
        username = self._data[self._conn_name]['user_' + k]
        password = self._data[self._conn_name]['pass_' + k]

        # Connect to message broker with user/pass.
        self._conn.connect(username, password, wait=True)

        # Consumers (clients) subscribe to the queue to listen for messages and must send acknowledgment for EVERY msg.
        if not self._producer:
            self._conn.subscribe(destination=self._data[self._conn_name]['queue'], id=1, ack='client-individual')
```

2. The second question is hard to tell because the MQ service is setup by the IT department in our organization. I don't have any visibility.  The only thing I know is that of the 3 hosts, only 1 of them is active at any given time (the other 2 will always refuse connection as they are failovers). If the current host goes down, one of the other two takes over. 

In previous release, I did not experience this problem. The reconnect would always succeed. Right now, I have a connection going since Oct 2, 2021 which has not disconnected so far. I'll continue to monitor

```
[2020-10-02 02:25:09]                       stomp.py     INFO - Sending frame: 'STOMP'
[2020-10-02 02:25:09]                       stomp.py     INFO - Received frame: 'CONNECTED', len(body)=0
[2020-10-02 02:25:09]                       stomp.py     INFO - Sending frame: 'SUBSCRIBE'
[2020-10-02 02:25:09] tvpv_portal.daemons.flash_mq_rqst_handler     INFO - Create pool with workers=2 to process messages
[2020-10-02 02:25:09] tvpv_portal.daemons.flash_mq_rqst_handler     INFO - Will run in infinite loop from now ... CTRL+C to quit

```

**Comment by pallavg** [comment]
We can close this issue. I was able to fix this by implementing reconnect/resubscribe in the on_receiver_loop() instead of the disconnected(). Now I no longer observe all 3 disconnects.
