### ISSUE TITLE
ConnectionRefusedError isn't being failover'd

### ISSUE THREAD

**Issue by tevert** [jasonrbriggs/stomp.py#333]
https://github.com/jasonrbriggs/stomp.py/blob/dev/stomp/transport.py#L793

When forming a connection, the Transport class will nicely loop over the provided addresses tuple until it finds a working address. 

However, it will only continue looping for socket timeouts. ConnectionRefusedErrors are unhandled, and just error-out. 

This comes up when using AWS's Amazon MQ. It provides two instances addresses for HA setup, but only one is active at any given time, and inactive one will refuse connections. 

Is this intended behavior? Let me know if you need a reproduction case. I'm on Python 3.6.9, stomp.py 6.1.0

**Comment by jasonrbriggs** [comment]
Isn't connection refused...

socket.error: [Errno 111] Connection refused

...in which case, it should still be handled.  What's the actual error you see?

**Comment by tevert** [comment]
Here's a test example:
```python
#!/usr/bin/env python3
import stomp
import traceback

# Note - at time of running, addr2 is the active instance, and addr1 refuses connection at the TCP level
addr1 = ("<AWS MQ Broker ID>-1.mq.us-west-2.amazonaws.com", "61614")
addr2 = ("<AWS MQ Broker ID>-2.mq.us-west-2.amazonaws.com", "61614")
username = '<user>'
password = '<password>'

def try_connect(addresses):
    try:
        conn = stomp.Connection(addresses)
        conn.set_ssl(addresses)
        conn.connect(username, password, wait=True)
        print('Successful connection')
        conn.disconnect()
    except Exception:
        print('Died with error:')
        traceback.print_exc()

print("CASE 1: -----------------------------------------------------------------------")
try_connect([ addr1, addr2 ])

print("CASE 2: -----------------------------------------------------------------------")
try_connect([ addr2, addr1 ])

print("CASE 3: -----------------------------------------------------------------------")
try_connect([ addr1 ])

print("CASE 4: -----------------------------------------------------------------------")
try_connect([ addr2 ])
```

```shell
$ ./test.py
CASE 1: -----------------------------------------------------------------------
Could not connect to host <AWS MQ Broker ID>-1.mq.us-west-2.amazonaws.com, port 61614
Traceback (most recent call last):
  File "/home/tevert/.local/lib/python3.6/site-packages/stomp/transport.py", line 737, in attempt_connection
    self.socket = socket.create_connection(host_and_port, self.__timeout)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Successful connection
CASE 2: -----------------------------------------------------------------------
Successful connection
CASE 3: -----------------------------------------------------------------------
Could not connect to host <AWS MQ Broker ID>-1.mq.us-west-2.amazonaws.com, port 61614
Traceback (most recent call last):
  File "/home/tevert/.local/lib/python3.6/site-packages/stomp/transport.py", line 737, in attempt_connection
    self.socket = socket.create_connection(host_and_port, self.__timeout)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Could not connect to host <AWS MQ Broker ID>-1.mq.us-west-2.amazonaws.com, port 61614
Traceback (most recent call last):
  File "/home/tevert/.local/lib/python3.6/site-packages/stomp/transport.py", line 737, in attempt_connection
    self.socket = socket.create_connection(host_and_port, self.__timeout)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Could not connect to host <AWS MQ Broker ID>-1.mq.us-west-2.amazonaws.com, port 61614
Traceback (most recent call last):
  File "/home/tevert/.local/lib/python3.6/site-packages/stomp/transport.py", line 737, in attempt_connection
    self.socket = socket.create_connection(host_and_port, self.__timeout)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Died with error:
Traceback (most recent call last):
  File "./test.py", line 16, in try_connect
    conn.connect(username, password, wait=True)
  File "/home/tevert/.local/lib/python3.6/site-packages/stomp/connect.py", line 161, in connect
    self.transport.start()
  File "/home/tevert/.local/lib/python3.6/site-packages/stomp/transport.py", line 105, in start
    self.attempt_connection()
  File "/home/tevert/.local/lib/python3.6/site-packages/stomp/transport.py", line 810, in attempt_connection
    raise exception.ConnectFailedException()
stomp.exception.ConnectFailedException
CASE 4: -----------------------------------------------------------------------
Successful connection
```

So this behavior is actually a bit different than my initial suspicion. 
When addr1 (inactive) is passed in on its own, it tries 3 times and then gives up, as expected. However, when I pass both addresses in, it gives up _immediately_, instead of attempting addr2. 


UPDATE: Good lord I need to get my eyes checked, I just now realized that case 1 also works fine. I thought I had seen some other behavior happening, but I'll close this for now, it seems like maybe the issue was somewhere else in my code. Sorry for the false alarm!
