### ISSUE TITLE
Unable to connect to servers that require client certificates (regression in 8.0.0)

### ISSUE THREAD

**Issue by mh21** [jasonrbriggs/stomp.py#373]
```text
Could not connect to host localhost, port 61614
Traceback (most recent call last):
  File "/home/mh21/git/cki/umb-messenger/.direnv/python-3.8.10/lib/python3.8/site-packages/stomp/transport.py", line 764, in attempt_connection
    check_ssl_certificate(host_and_port)
  File "/home/mh21/git/cki/umb-messenger/.direnv/python-3.8.10/lib/python3.8/site-packages/stomp/transport.py", line 55, in check_ssl_certificate
    cert = ssl.get_server_certificate((host, port))
  File "/usr/lib/python3.8/ssl.py", line 1484, in get_server_certificate
    with context.wrap_socket(sock) as sslsock:
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)
Traceback (most recent call last):
  File "rabbitmq_reproducer.py", line 16, in <module>
    connection.connect(wait=True)
  File "/home/mh21/git/cki/umb-messenger/.direnv/python-3.8.10/lib/python3.8/site-packages/stomp/connect.py", line 150, in connect
    self.transport.start()
  File "/home/mh21/git/cki/umb-messenger/.direnv/python-3.8.10/lib/python3.8/site-packages/stomp/transport.py", line 130, in start
    self.attempt_connection()
  File "/home/mh21/git/cki/umb-messenger/.direnv/python-3.8.10/lib/python3.8/site-packages/stomp/transport.py", line 834, in attempt_connection
    raise exception.ConnectFailedException()
stomp.exception.ConnectFailedException
```

Reproducer via RabbitMQ/podman:
- [reproducer.zip](https://github.com/jasonrbriggs/stomp.py/files/8212618/reproducer.zip)
- extract archive, `pip install stomp.py==8.0.0`, start and configure RabbitMQ via `./rabbitmq_service.sh` and run the reproducer via `HOST_RABBITMQ_SERVICE_DIR=/tmp/rabbitmq-service-dir python3 rabbitmq_reproducer.py`

This worked in stomp 7.0.0. 

The underlying reason is the added call to `check_ssl_certificate`, which calls `ssl.get_server_certificate`, which does not work if the server requires client certificates.

Workaround:
- disable `check_ssl_certificate` via `stomp.transport.check_ssl_certificate = lambda *_, **__: None`

Let me know if you have any questions!

For background, this came up while investigating ActiveMQ stomp connection failures at https://gitlab.com/cki-project/umb-messenger/-/merge_requests/71.

**Comment by jasonrbriggs** [comment]
Fixed on dev branch.

**Comment by mh21** [comment]
> Fixed on dev branch.

Thank you very much! 🤗
