### ISSUE TITLE
An error occurred when running the stompy example

### ISSUE THREAD

**Issue by Tsxiaolei** [jasonrbriggs/stomp.py#412]
I'm running a stompy example. When I run the "python stomptest.py This is a test" command according to the document, the following error message is displayed:
---------------------------
No handlers could be found for logger "stomp.py"
('what is self.socket', None)
Traceback (most recent call last):
  File "stomptest.py", line 15, in <module>
    conn.connect('admin', 'password', wait=True)
  File "/home/li/teststomp/lib/python2.7/site-packages/stomp/connect.py", line 174, in connect
    self.transport.start()
  File "/home/li/teststomp/lib/python2.7/site-packages/stomp/transport.py", line 111, in start
    self.attempt_connection()
  File "/home/li/teststomp/lib/python2.7/site-packages/stomp/transport.py", line 810, in attempt_connection
    raise exception.ConnectFailedException()
stomp.exception.ConnectFailedException
-----------------------------
Is there any solution?Thanks.

The document address is:http://jasonrbriggs.github.io/stomp.py/quickstart.html#stomp-py-api
os==CentOS Linux
stomp==4.1.24
Python == 2.7.5

**Comment by jasonrbriggs** [comment]
This like an error in your code.  The example code works fine when I test it with activemq for example.
