### ISSUE TITLE
'sys' is not defined in listener.py

### ISSUE THREAD

**Issue by SamFinnigan** [jasonrbriggs/stomp.py#61]
Using latest library version, on line 231 there is a call to sys.exc_info(), but sys has not been imported.

```
Traceback (most recent call last):                                             
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner       
    self.run()                                                                 
  File "/usr/lib/python2.7/threading.py", line 763, in run                     
    self.__target(*self.__args, **self.__kwargs)                               
  File "/usr/local/lib/python2.7/dist-packages/stomp/listener.py", line 231, in
 __heartbeat_loop                                                              
    _, e, _ = sys.exc_info()                                                   
NameError: global name 'sys' is not defined
```

Solution: add `import sys` at the top?

**Comment by jasonrbriggs** [comment]
Fixed in 4.1.8. Thanks for the report.
