### ISSUE TITLE
on_before_message

### ISSUE THREAD

**Issue by coreground** [jasonrbriggs/stomp.py#99]
Decided to remove this message:
DEBUG:stomp.py:listener <__main__.stompworkerListener object at 0x7f42cba13650> has no method on_before_message

so I implemented a simple logging function and it exposes this:

        INFO:stomp.py:Receiver loop ended
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/stomp/transport.py", line 312, in __receiver_loop
    self.process_frame(f, frame)
  File "/usr/local/lib/python2.7/dist-packages/stomp/transport.py", line 166, in process_frame
    (f.headers, f.body) = self.notify('before_message', f.headers, f.body)
TypeError: 'NoneType' object is not iterable

**Comment by jasonrbriggs** [comment]
Fixed in the next release.
